  name: test-and-connect-publish
  on:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]

  jobs:
    test-and-connect-publish:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
        - name: Set Up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
        - name: Render And Publish
          uses: quarto-dev/quarto-actions/publish@v2
            with:
              target: posit-cloud
              path: quartodemo.qmd
              POSIT_CLOUD_TOKEN: F69A5954CC09A97B7D74C73C6C7384EB
              POSIT_CLOUD_SECRET: ${{ secrets.CONNECT_API_KEY }}

